// Authentication 
export const AUTH_USER = 'AUTH_USER';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = 'LOGOUT';
export const SYNC_CURRENT_USER = 'SYNC_CURRENT_USER';


// Error Messages
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Department 

export const OPEN_NEW_FORM = 'OPEN_NEW_FORM';
export const CLOSE_NEW_FORM = 'CLOSE_NEW_FORM';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
export const FETCH_COMPANY_DEPARTMENT = 'FETCH_COMPANY_DEPARTMENT';
export const ERROR_DEPARTMENT = 'ERROR_DEPARTMENT';



// Employee
export const GET_ADD_USER = 'GET_ADD_USER';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';

//  Timer
export const GET_TIMER_REPORT = 'GET_TIMER_REPORT';
export const TIMER_ON = 'TIMER_ON';
export const TIMER_OFF = 'TIMER_OFF';
export const SET_WORKED_MILLISECOND = 'SET_WORKED_MILLISECOND';

// Task
export const FETCH_TASKS_PENDING = 'FETCH_TASKS_PENDING';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const MARK_COMPLETE = 'MARK_COMPLETE';
export const ACCEPT_TASK = 'ACCEPT_TASK';
export const TOGGLE_TASK_COMPLETE = 'TOGGLE_TASK_COMPLETE';


export const ASSIGN_TASKS = 'ASSIGN_TASKS';
export const GET_ACCEPTED_TASKS = 'GET_ACCEPTED_TASKS';

// Todo
export const FETCH_TODOS_PENDING = 'FETCH_TODO_PENDING';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODO_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODO_ERROR';
export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const OPEN_TODO_FORM = 'OPEN_TODO_FORM';
export const CLOSE_TODO_FORM = 'CLOSE_TODO_FORM';
export const TOGGLE_TODO_COMPLETE = 'TOGGLE_TODO_COMPLETE';